### ISSUE TITLE
Loading of assets seems broken

### ISSUE THREAD

**Issue by RealWarrior03** [brufdev/many-notes#2]
![image](https://github.com/user-attachments/assets/85acb638-b9a7-4ff1-9bbb-ada53fd2b32d)

the given error is thrown when loading the page.
I assumed that I have to enter the IP that the mariadb container receives?
Or what do I have to do with the following information:
![image](https://github.com/user-attachments/assets/1dc39eb7-6631-45ad-b650-92361cfc19a6)

**Comment by brufdev** [comment]
If you change the default port from 80 or use a reverse proxy with a custom URL, ensure you update both APP_URL and ASSET_URL accordingly. For example, if you set the port to 9999, your URLs should be updated to:

```
- APP_URL=http://localhost:9999
- ASSET_URL=http://localhost:9999
```

I will be releasing a new version soon, which will feature simplified and better-explained installation steps. Please let me know if this resolved your issue.

**Comment by RealWarrior03** [comment]
yup, that was the sole problem..
forgot to list the custom port
